version: '3.7'

services:
  carwash_service:
    build: ./carwash-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 3000
    volumes:
      - ./carwash-service/:/app/
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URI=postgresql://postgres:1234@postgres/carwash_db
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=carwash_db

volumes:
  postgres_data:
